# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '^(docs/source/|tutorials_and_tools/_build/)'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb=2000"]
-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    -   id: black
        exclude: '^tutorials_and_tools/'
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0 # Use the desired flake8 version
    hooks:
    -   id: flake8
        exclude: '^tutorials_and_tools/'
